name       : qt6-serialport
version    : 6.2.1
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.1/submodules/qtserialport-everywhere-src-6.2.1.tar.xz : ec77f4c9d6096588f3e735315f873976103479be453985b27f27fe8994e0776a
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Qt6 Serial Port Module
description: |
    Qt6 Serial Port provides the basic functionality, which includes configuring, I/O operations, getting and setting the control signals of the RS-232 pinouts.
builddeps  :
    - pkgconfig(Qt6Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
